server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name www.filestamper.com filestamper.com;

    ssl_certificate /etc/letsencrypt/live/filestamper.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/filestamper.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/jrod2/file_sorter/file_sorter.sock;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name www.filestamper.com filestamper.com;

    return 301 https://$host$request_uri;
}

